### ISSUE TITLE
Ficheros de configuracion de Splunk

### ISSUE THREAD

**Issue by Yolabn** [SantaKa0S/kaos#480]
Añadiendo los ficheros de configuración:
- deploymentclient.conf
- inputs.conf
- outputs.conf

**Comment by santakloud** [comment]
Ka0S has been initiated by Yolabn.
 launch by Yolabn
Branch name is refs/heads/H480-ficheros-de-configuracion-de-splunk
Commit SHA is 81403e18dcafb128252d46f09c514e0eea4e6ef5
Repo origin is SantaKa0S/kaos
Assigned number issue 480
Executed flow about H
**Please check the job logs for https://github.com/SantaKa0S/kaos/actions/runs/12256698075**
**Workflow Name:** Ka0S
**Job Name:** job-flows
**Run ID:** 12256698075
**Run Number:** 319
**Repository:** SantaKa0S/kaos
**Branch:** refs/heads/H480-ficheros-de-configuracion-de-splunk
**Commit:** 81403e18dcafb128252d46f09c514e0eea4e6ef5
**Actions Involved:**
**Ref Flow: H**
**Ref Issue: 480**
**Please review issue 480 for more information.**

**Comment by santakloud** [comment]
This is a issue created by [Ka0S] INIT to register Actions workflows **Ka0s Init**.
It has been requested by: **santakloud**

**Message:**


**Workflow Name:** Ka0s Init
**Job Name:** kaos-init-process
**Run ID:** 12256705388
**Run Number:** 343
**Repository:** SantaKa0S/kaos
**Branch:** refs/heads/H480-ficheros-de-configuracion-de-splunk
**Commit:** 372455b9b61cb56ebd53f66d269b1e6392343685

**Files Involved:**

**Comment by santakloud** [comment]
Launch workflow yamllint.yaml
